config/routes.rb
Rails.application.routes.draw do
  resources :people, only: [:index, :show, :update]
  namespace :api do
    resources :temporary_people , only: [:index, :show, :update]
  end
  resources :api_people, only: [:index]
  root 'people#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :people, dependent: :destroy

  with_options presence: true do |o|
    o.validates :location
    o.validates :title, length: { maximum: 255 }
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :organization
  validates :organization, presence: true

  with_options presence: true do |p|
    p.validates :first_name, length: { maximum: 255 }
    p.validates :last_name, length: { maximum: 255 }
  end
  validates :assessement_count, numericality: { only_integer: true, greater_then_or_equal_to: 0 }
end

app/controllers/api/temporary_people_controller.rb
class Api::TemporaryPeopleController < ApplicationController
  skip_before_filter :verify_authenticity_token, if: :json_only

  def index
    q = Person.search(params[:q])
    people = q.result(distinct: true)
    render json: { status: "success",
                   response: people.map{ |p| PersonSerializer.new(p) } }
  end

  def show
    person = Person.find(params[:id])
    render json: { status: "success", response: PersonSerializer.new(person) }
  end

  def update
    person = Person.find(params[:id])
    if person.update person_params
      render json: { status: "success", response: PersonSerializer.new(person) }
    else
      render json: { errors: person.errors.full_messages }
    end
  end

  protected
  def json_only
    request.format.json?
  end

  private

  def person_params
    params.require(:person).permit(:first_name, :last_name, :organization_id)
  end
end

app/controllers/api_people_controller.rb
class ApiPeopleController < ApplicationController
  def index
    uri = URI.parse('http://assessapp.herokuapp.com/api/temporary_people?q%5Bs%5D=last_name+as')
    res = Net::HTTP.get_response(uri)
    @api_people = []
    if res.is_a?(Net::HTTPSuccess)
      parsed = JSON.parse(res.body)
      @api_people = parsed['response']
      @api_people = @api_people.map{|k| k['person'] if k['person']['assessment_count'] > 0 and k['person']['organisation']['title'].include? "ABC"}.compact
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @q = Person.search(params[:q])
    @people = @q.result(distinct: true)
  end

  def show
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update person_params
      render json: { success: true }
    else
      render json: @person.errors.messages
    end
  end

private
  def person_params
    params.require(:person).permit(:first_name, :last_name, :organization_id)
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def index
    @q = Person.search(params[:q])
    @persons = @q.result(distinct: true)
  end

  def show
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update person_params
      render json: { success: true }
    else
      render json: @person.errors.messages
    end
  end

private
  def person_params
    params.require(:person).permit(:first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/api_people/_person.html.haml
%tr
  %td= person['id']
  %td= person['first_name']
  %td= person['last_name']
  %td= person['assessment_count']
  %td= person['organisation']['title']

app/views/api_people/index.html.haml
%h1
  People from api
%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th= 'ID'
      %th= 'First Name'
      %th= 'Last Name'
      %th= 'Assessement Count'
      %th= 'Ogranization Title'
  %tbody
    = render partial: "person", collection: @api_people

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SimpleWebpage
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
  %body
    = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/people/_edit_person.html.haml
#edit_person.modal.fade{ role: 'dialog' }
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ 'data-dismiss' => 'modal'} &times;
        %h4.modal-title Edit Person
      .modal-body
        = form_for @person, html: { class: 'form-horizontal', id: 'edit_person_form' } do |f|
          .form-group
            = f.label :first_name, 'First Name', class: 'control-label col-sm-3'
            .col-sm-9
              = f.text_field :first_name, value: @person.first_name, class: 'form-control'
          .form-group
            = f.label :last_name, 'Last Name', class: 'control-label col-sm-3'
            .col-sm-9
              = f.text_field :last_name, value: @person.last_name, class: 'form-control'
          .form-group
            = f.label :organization_id, 'Organization', class: 'control-label col-sm-3'
            .col-sm-9
              = f.select :organization_id, Organization.all.map{|o| [o.title, o.id]}, {}, { class: 'form-control' }
          .form-group
            .col-sm-offset-3.col-sm-9
              %button.btn.btn-default{type: 'submit'} Update

app/views/people/_person.html.haml
%tr
  %td= person.id
  %td= link_to person.first_name, person
  %td= person.last_name
  %td= person.organization_id
  %td= person.assessement_count

app/views/people/index.html.haml
%h1
  People
%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th= 'ID'
      %th= sort_link(@q, :first_name, 'first_name')
      %th= sort_link(@q, :last_name, 'last_name')
      %th= 'organization_id'
      %th= 'assessement_count'
  %tbody
    = render partial: "person", collection: @people
= link_to "People from api", api_people_path, class: 'btn'

app/views/people/show.html.haml
%h1 Personal details
%table.table-bordered.table-condensed
  %tr
    %th= 'First Name'
    %td= @person.first_name
  %tr
    %th= 'Last Name'
    %td= @person.last_name
  %tr
    %th= 'Organization'
    %td= @person.organization.title
  %tr
    %th= 'Location'
    %td= @person.organization.location

= link_to 'Edit data', '#edit_person', 'data-toggle' => 'modal', :class => 'btn'
= render 'people/edit_person'

app/views/persons/index.html.haml
%h1
  Persons
%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th= 'ID'
      %th= sort_link(@q, :first_name, 'first_name')
      %th= sort_link(@q, :last_name, 'last_name')
      %th= 'organization_id'
      %th= 'assessement_count'
  %tbody
    = render partial: "person", collection: @persons

app/views/persons/show.html.haml
%h1 Personal details
%table.table-bordered.table-condensed
  %tr
    %th= 'First Name'
    %td= @person.first_name
  %tr
    %th= 'Last Name'
    %td= @person.last_name
  %tr
    %th= 'Organization'
    %td= @person.organization.title
  %tr
    %th= 'Location'
    %td= @person.organization.location

= link_to 'Edit data', '#edit_person', 'data-toggle' => 'modal', :class => 'btn'
-#%button.btn.btn-link{ type: 'button', 'data-toggle' => 'modal', 'data-target' => '#edit_person' } Edit data
= render 'persons/edit_person'